### ISSUE TITLE
Synchronization issue when participant id is changed

### ISSUE THREAD

**Issue by benterich** [cozie-app/cozie-apple#83]
**Describe the bug**
I am currently testing my study. This means that I change the participant Id on the phone to a different identifier each time I test a different iteration or feature. But, this time, it cannot find a connection to my watch and the icon in the phone app is grey.

**To Reproduce**
I opened Cozie on my watch
I opened Cozie on my phone
I changed the Participant ID 
I synchronized the backend tab
I synchronized the Settings tab
I synchronized the Watch Survey Tab
I did a few surveys

**Comments**
I also tested turning off the Bluetooth. No change
I also tested shutting all apps down doing a soft reset on the phone and watch. No Change.
I changed Settings in the Cozie App which also did not have an effect. No Change.

**Expected behavior**
I would have expected a orange icon next to the participant id and the survey count to increase.

**Screenshots**
<img width="768" alt="Untitled" src="https://github.com/cozie-app/cozie-apple/assets/133053340/64fac051-a6ca-4814-886e-c0708532c93d">

**Smartphone (please complete the following information):**
 - Device: iphoneSE, Watch Series 7
 - OS: 9.6.3
 - Version: Cozie V3

**Comment by benterich** [comment]
Addition:
I just checked, it also did not submit the survey data to the previous set participant id.

**Comment by mariofrei** [comment]
Hi @benterich,
Thank you for your feedback. 
Your attempts to fix the issue are in line with the [troubleshooting guide](https://cozie-apple.app/docs/troubleshooting/#the-cozie-setting-cannot-be-synced-between-the-iphone-and-the-apple-watch).
So, at this point, I can only recommend removing the Cozie app from the iPhone and the Apple Watch and then installing it again.

**Comment by benterich** [comment]
Reinstalling both the phone app and watch app fixed the issue.
