### ISSUE TITLE
skin temperature

### ISSUE THREAD

**Issue by jli113** [cozie-app/cozie-apple#84]
**Is your feature request related to a problem? Please describe.**
track skin temperature

**Describe the solution you'd like**
use wrist_temperature to track body temperature

**Describe alternatives you've considered**

**Additional context**

**Comment by mariofrei** [comment]
Hi @jli113,
Thank you for the feature request.
Skin temperature is already available. Currently, one skin temperature value per night is available. See `ws_wrist_temperature` and `ts_wrist_temperature` in the [documentation](https://cozie-apple.app/docs/download_data/data_overview).
Unfortunately, the HealthKit API does not provide wrist temperature data with a higher sampling rate. Unless Apple changes the API, there is nothing we can currently do to improve the situation.
